batch_size: 20000
ckpt_path: null
dataset_name: spot_online
distortion_loss_w: 0
downsample: 1.0
eval_lpips: false
exp_name: Spot
lr: 0.01
no_save_test: false
num_epochs: 2
num_gpus: 1
optimize_ext: false
random_bg: false
ray_sampling_strategy: all_images
root_dir: ../../../../robot/spot_data_/spot_data_0/
scale: 0.5
split: train
use_exposure: false
val_only: false
weight_path: null
